export const productSections = [
  {
  key: "gaming-laptops",
  title: "Best Gaming Laptops Under ₹90,000",
  accent: "#4ade80",
  items: [
    {
      id: 1,
      tag: "TOP PICK",
      tagColor: "#4ade80",
      title: "Lenovo LOQ 2024",
      subtitle: "i5-12450HX · RTX 3050 (6GB) · 16GB RAM",
      bestFor: "Students, Coding & Gaming",
      avoidIf: "You need lightweight daily carry",
      saverNestScore: {
        overall: 9.1,
        value: 9.4,
        performance: 9.0,
        reliability: 8.8,
      },
      reason: {
        summary:
          "Best overall gaming laptop for students offering strong RTX graphics, HX-series CPU performance, and excellent price-to-power balance.",
        pros: [
          "RTX 3050 6GB handles modern games smoothly",
          "HX processor stronger than typical H-series CPUs",
          "16GB RAM ideal for coding and multitasking",
        ],
        cons: ["Slightly heavier for daily travel"],
      },
      trustLine: "Best value gaming laptop right now",
      updatedAt: "Checked this week",
      price: "₹74,990",
      oldPrice: "₹89,990",
      save: "Save ₹15,000",
      image: "https://m.media-amazon.com/images/I/81tmCrtiRgL._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#4ade80",
      link: "https://amzn.to/4c2bUU7",
    },

    {
      id: 2,
      tag: "EDITOR PICK",
      tagColor: "#22d3ee",
      title: "Dell G15 (13th Gen)",
      subtitle: "i5-13450HX · RTX 3050 (6GB) · 16GB RAM",
      bestFor: "Office + Gaming + Long-term reliability",
      avoidIf: "You want lightweight laptop",
      saverNestScore: {
        overall: 8.9,
        value: 8.6,
        performance: 9.2,
        reliability: 9.0,
      },
      reason: {
        summary:
          "Strong processor performance with reliable Dell build quality, making it ideal for long-term gaming and professional workloads.",
        pros: [
          "13th Gen HX processor excellent for heavy tasks",
          "1TB SSD gives strong storage advantage",
          "Trusted Dell durability and cooling",
        ],
        cons: ["Heavier than competitors"],
      },
      trustLine: "Most reliable performance pick",
      updatedAt: "Checked this week",
      price: "₹84,990",
      oldPrice: "₹99,990",
      save: "Save ₹15,000",
      image: "https://m.media-amazon.com/images/I/61ko2a0owDL._SL1080_.jpg",
      cta: "Check today’s price",
      accent: "#22d3ee",
      link: "https://amzn.to/4v6wQlA",
    },

    {
      id: 3,
      tag: "GAMING PICK",
      tagColor: "#f59e0b",
      title: "ASUS TUF A15 (2025)",
      subtitle: "Ryzen 7 7445HS · RTX 3050 · 16GB DDR5",
      bestFor: "Gaming & Engineering students",
      avoidIf: "You want MS Office included",
      saverNestScore: {
        overall: 8.8,
        value: 8.7,
        performance: 9.1,
        reliability: 8.4,
      },
      reason: {
        summary:
          "Powerful Ryzen 7 processor with strong gaming thermals and upgradeable DDR5 RAM makes this ideal for long-term performance users.",
        pros: [
          "Ryzen 7 CPU excellent for multitasking",
          "Upgradeable RAM up to 64GB",
          "Strong gaming thermal design",
        ],
        cons: ["RTX 3050 is 4GB variant"],
      },
      trustLine: "Best Ryzen gaming option",
      updatedAt: "Checked this week",
      price: "₹79,990",
      oldPrice: "₹94,990",
      save: "Save ₹15,000",
      image: "https://m.media-amazon.com/images/I/81nPkLHN3vL._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#f59e0b",
      link: "https://amzn.to/3PKr1dy",
    },
  ],
},
  {
  key: "mobiles",
  title: "Best Phones Worth Buying Right Now",
  accent: "#60a5fa",
  items: [
    {
      id: 4,
      tag: "BEST OVERALL",
      tagColor: "#60a5fa",
      title: "Motorola Edge 70 Fusion",
      subtitle: "Snapdragon 7s Gen 4 · 8GB RAM · 144Hz AMOLED",
      bestFor: "Overall performance & battery life",
      avoidIf: "You want the strongest brand trust or flagship-level camera consistency",
      saverNestScore: {
        overall: 8.7,
        value: 9.1,
        performance: 8.5,
        reliability: 7.9,
      },
      reason: {
        summary:
          "Best overall choice if you want a strong display, smooth daily performance, big battery, and solid value under ₹30,000.",
        pros: [
          "Large 7000mAh battery is excellent for long daily use",
          "144Hz AMOLED display feels smooth and premium",
          "Balanced performance for gaming, media, and daily tasks",
        ],
        cons: ["Lower buyer confidence because of limited rating count right now"],
      },
      trustLine: "Best overall value pick",
      updatedAt: "Checked this week",
      price: "₹26,999",
      oldPrice: "₹42,999",
      save: "Save ₹16,000",
      image: "https://m.media-amazon.com/images/I/41ScDr67t5L.jpg",
      cta: "Check today’s price",
      accent: "#60a5fa",
      link: "https://amzn.to/4sI1S1z",
    },
    {
      id: 5,
      tag: "VALUE PICK",
      tagColor: "#a78bfa",
      title: "Nothing Phone (3a) Lite",
      subtitle: "8GB RAM · 128GB Storage · Clean UI",
      bestFor: "Clean software & stylish daily use",
      avoidIf: "You want top gaming performance or premium camera hardware",
      saverNestScore: {
        overall: 8.3,
        value: 8.8,
        performance: 7.9,
        reliability: 8.2,
      },
      reason: {
        summary:
          "Best value choice for buyers who want a clean software experience, attractive design, and a balanced everyday phone near ₹20,000.",
        pros: [
          "Clean Nothing OS gives a smoother daily experience",
          "Good value for users who want a fresh, modern design",
          "Balanced pick for social media, calling, and normal use",
        ],
        cons: ["Not the strongest choice for heavy gaming or advanced camera needs"],
      },
      trustLine: "Best clean UI value",
      updatedAt: "Checked this week",
      price: "₹20,235",
      oldPrice: "₹22,999",
      save: "Save ₹2,764",
      image: "https://m.media-amazon.com/images/I/717B2B7Hm8L._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#a78bfa",
      link: "https://amzn.to/4vlOW3g",
    },
    {
      id: 6,
      tag: "CAMERA PICK",
      tagColor: "#f87171",
      title: "Samsung Galaxy S24 FE 5G",
      subtitle: "8GB RAM · 128GB Storage · AI Camera Phone",
      bestFor: "Camera, premium feel & long-term trust",
      avoidIf: "You want the lowest price or biggest battery value",
      saverNestScore: {
        overall: 9.0,
        value: 8.2,
        performance: 8.8,
        reliability: 9.3,
      },
      reason: {
        summary:
          "Best camera-focused and most trusted premium pick here if you want stronger brand confidence, better imaging, and a more flagship-like experience.",
        pros: [
          "Strong Samsung camera performance for photos and video",
          "High buyer trust with strong review volume",
          "More premium overall experience than typical mid-range phones",
        ],
        cons: ["Much more expensive than the other two options"],
      },
      trustLine: "Best camera and trust pick",
      updatedAt: "Checked this week",
      price: "₹38,909",
      oldPrice: "₹59,999",
      save: "Save ₹21,090",
      image: "https://m.media-amazon.com/images/I/71eUNTW+nJL._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#f87171",
      link: "https://amzn.to/4do4dKn",
    },
  ],
},
  {
  key: "audio",
  title: "Best Audio Devices Under ₹5,000",
  accent: "#f87171",
  items: [
    {
      id: 7,
      tag: "BEST SPEAKER",
      tagColor: "#f87171",
      title: "JBL Flip Essential 2",
      subtitle: "Deep bass · IPX7 waterproof · Premium sound",
      bestFor: "Travel, parties & outdoor listening",
      avoidIf: "You need calling support (no mic)",
      saverNestScore: {
        overall: 9.1,
        value: 8.8,
        performance: 9.3,
        reliability: 9.4,
      },
      reason: {
        summary:
          "Best portable Bluetooth speaker under ₹5,000 with strong bass, waterproof build, and trusted JBL sound quality.",
        pros: [
          "Excellent deep bass and loud output",
          "IPX7 waterproof for outdoor use",
          "Very high Amazon rating with strong buyer trust",
        ],
        cons: ["No built-in microphone for calls"],
      },
      trustLine: "Most trusted speaker under 5k",
      updatedAt: "Checked this week",
      price: "₹4,999",
      oldPrice: "₹9,999",
      save: "Save ₹5,000",
      image: "https://m.media-amazon.com/images/I/51bfIuFGCAL._SL1080_.jpg",
      cta: "Check today’s price",
      accent: "#f87171",
      link: "https://amzn.to/4sfV2iN",
    },

    {
      id: 8,
      tag: "BEST NECKBAND",
      tagColor: "#4ade80",
      title: "OnePlus Bullets Wireless Z2 ANC",
      subtitle: "45dB ANC · 28hr battery · 12.4mm drivers",
      bestFor: "Calls, travel & daily commute",
      avoidIf: "You want truly wireless earbuds",
      saverNestScore: {
        overall: 8.8,
        value: 9.4,
        performance: 8.6,
        reliability: 9.0,
      },
      reason: {
        summary:
          "Best neckband under ₹2,000 offering strong ANC performance, excellent battery life, and reliable call quality.",
        pros: [
          "45dB hybrid ANC is rare at this price",
          "Very strong battery backup (28 hours)",
          "Fast charging gives hours of playback quickly",
        ],
        cons: ["Not fully wireless like earbuds"],
      },
      trustLine: "Best ANC neckband value",
      updatedAt: "Checked this week",
      price: "₹1,899",
      oldPrice: "₹2,499",
      save: "Save ₹600",
      image: "https://m.media-amazon.com/images/I/51xJvaON00L._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#4ade80",
      link: "https://amzn.to/4ch7yK5",
    },

    {
      id: 9,
      tag: "BEST EARBUDS",
      tagColor: "#22d3ee",
      title: "realme Buds T310",
      subtitle: "46dB ANC · Spatial audio · 40hr battery",
      bestFor: "Music, gaming & daily wireless use",
      avoidIf: "You want premium flagship earbuds",
      saverNestScore: {
        overall: 8.7,
        value: 9.2,
        performance: 8.5,
        reliability: 8.4,
      },
      reason: {
        summary:
          "Best true wireless earbuds under ₹2,000 with strong ANC, spatial audio support, and long battery life.",
        pros: [
          "46dB ANC improves listening experience",
          "Spatial audio adds immersive sound",
          "Up to 40 hours total battery backup",
        ],
        cons: ["Case build feels less premium than higher-end models"],
      },
      trustLine: "Best earbuds under 2k",
      updatedAt: "Checked this week",
      price: "₹1,999",
      oldPrice: "₹3,999",
      save: "Save ₹2,000",
      image: "https://m.media-amazon.com/images/I/61zmvJ9l56L._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#22d3ee",
      link: "https://amzn.to/4vdI8EP",
    },
  ],
},
  {
  key: "wearables",
  title: "Best Smartwatches Under ₹5,000",
  accent: "#a78bfa",
  items: [
    {
      id: 10,
      tag: "BEST OVERALL",
      tagColor: "#a78bfa",
      title: "Noise ColorFit Pro 5 Max",
      subtitle: "1.96” AMOLED · BT Calling · VO2 Max",
      bestFor: "Overall smartwatch value under ₹5,000",
      avoidIf: "You want flagship-level tracking accuracy",
      saverNestScore: {
        overall: 8.5,
        value: 8.8,
        performance: 8.3,
        reliability: 8.1,
      },
      reason: {
        summary:
          "Best overall smartwatch pick under ₹5,000 if you want AMOLED display, Bluetooth calling, and strong health-focused features in one package.",
        pros: [
          "1.96-inch AMOLED display looks sharp and premium",
          "Bluetooth calling adds real daily convenience",
          "VO2 Max and workout analysis improve fitness value",
        ],
        cons: ["Health tracking accuracy may not match premium brands"],
      },
      trustLine: "Best overall smartwatch under 5k",
      updatedAt: "Checked this week",
      price: "₹3,999",
      oldPrice: "₹9,999",
      save: "Save ₹6,000",
      image: "https://m.media-amazon.com/images/I/61IYppaanVL._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#a78bfa",
      link: "https://amzn.to/4sJAJez",
    },
    {
  id: 11,
  tag: "WOMEN'S PICK",
  tagColor: "#4ade80",
  title: "Noise Diva 2 Smart Watch",
  subtitle: "36mm AMOLED · BT Calling · Cycle Tracker",
  bestFor: "Women looking for stylish smartwatch with health tracking",
  avoidIf: "You prefer large-dial sporty watches",
  saverNestScore: {
    overall: 8.4,
    value: 8.6,
    performance: 8.1,
    reliability: 8.2,
  },
  reason: {
    summary:
      "Best smartwatch under ₹5,000 for women offering a sleek AMOLED display, female health tracking, and Bluetooth calling in a lightweight stylish design.",
    pros: [
      "Slim 36mm dial designed for comfortable daily wear",
      "Female cycle tracker adds practical health value",
      "AMOLED display improves visibility and premium feel",
    ],
    cons: ["Smaller dial may not suit users who prefer large displays"],
  },
  trustLine: "Best smartwatch for women under 5k",
  updatedAt: "Checked this week",
  price: "₹3,499",
  oldPrice: "₹6,999",
  save: "Save ₹3,500",
  image: "https://m.media-amazon.com/images/I/712ZKoaOECL._SL1500_.jpg",
  cta: "Check today’s price",
  accent: "#4ade80",
  link: "https://amzn.to/4ttrOy1",
},
    {
      id: 12,
      tag: "BUDGET PICK",
      tagColor: "#f59e0b",
      title: "boAt Storm Call 3",
      subtitle: "BT Calling · 700+ Active Modes · 1.83” HD",
      bestFor: "Budget buyers and calling-focused users",
      avoidIf: "You want AMOLED display or premium build",
      saverNestScore: {
        overall: 8.2,
        value: 9.1,
        performance: 7.8,
        reliability: 8.3,
      },
      reason: {
        summary:
          "Best budget smartwatch under ₹1,500 if you want Bluetooth calling, activity tracking, and a large display at a very low price.",
        pros: [
          "Very aggressive pricing for the features offered",
          "Bluetooth calling is useful in day-to-day use",
          "Huge review volume gives stronger buyer trust",
        ],
        cons: ["Display and finish are less premium than AMOLED rivals"],
      },
      trustLine: "Best budget calling smartwatch",
      updatedAt: "Checked this week",
      price: "₹1,099",
      oldPrice: "₹8,499",
      save: "Save ₹7,400",
      image: "https://m.media-amazon.com/images/I/61A9rFdBjtL._SL1500_.jpg",
      cta: "Check today’s price",
      accent: "#f59e0b",
      link: "https://amzn.to/415Gkjk",
    },
  ],
},
];