export const productSections = [
  {
    key: "laptops",
    title: "Best Laptops Under ₹50,000",
    accent: "#4ade80",
    items: [
      {
        id: 1,
        tag: "BEST PICK",
        tagColor: "#4ade80",
        title: "HP Pavilion Laptop",
        subtitle: "i5 · 8GB RAM · 512GB SSD",
        bestFor: "Students & Office Work",
        avoidIf: "Heavy editing or gaming",
        saverNestScore: {
          overall: 8.3,
          value: 8.5,
          performance: 7.8,
          reliability: 8.6,
        },
        reason: {
          summary:
            "Best for students and office users who want reliable day-to-day performance under ₹50,000.",
          pros: [
            "Solid choice for study and office tasks",
            "Fast SSD keeps boot and app load times smooth",
            "Reliable everyday laptop for normal workloads",
          ],
          cons: ["8GB RAM is weaker for heavy multitasking or editing"],
        },
        trustLine: "Best overall balance",
        updatedAt: "Checked this week",
        price: "₹45,999",
        oldPrice: "₹52,999",
        save: "Save ₹7,000",
        image:
          "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#4ade80",
        link: "#",
      },
      {
        id: 2,
        tag: "EDITOR PICK",
        tagColor: "#22d3ee",
        title: "ASUS Vivobook 15",
        subtitle: "Ryzen 5 · 16GB RAM · SSD",
        bestFor: "Coding & Multitasking",
        avoidIf: "You want the lightest laptop",
        saverNestScore: {
          overall: 8.6,
          value: 8.8,
          performance: 8.5,
          reliability: 8.0,
        },
        reason: {
          summary:
            "Best value choice if you want more RAM for coding, multitasking, and long-term use.",
          pros: [
            "16GB RAM is strong for this budget",
            "Good for coding and daily multitasking",
            "Better long-term usability than 8GB options",
          ],
          cons: ["Not the lightest option in this category"],
        },
        trustLine: "Best RAM under 50k",
        updatedAt: "Checked this week",
        price: "₹49,990",
        oldPrice: "₹58,990",
        save: "Save ₹9,000",
        image:
          "https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#22d3ee",
        link: "#",
      },
      {
        id: 3,
        tag: "VALUE PICK",
        tagColor: "#f59e0b",
        title: "Lenovo IdeaPad Slim",
        subtitle: "Student workhorse · Lightweight",
        bestFor: "Daily carry & college use",
        avoidIf: "You need heavy creative power",
        saverNestScore: {
          overall: 8.1,
          value: 8.7,
          performance: 7.4,
          reliability: 8.1,
        },
        reason: {
          summary:
            "Best lightweight option if your priority is portability and everyday reliability.",
          pros: [
            "Easy to carry daily for college or office",
            "Good fit for study and basic work tasks",
            "Balanced value for buyers who want portability first",
          ],
          cons: ["Not meant for heavy creative workloads or gaming"],
        },
        trustLine: "Best lightweight pick",
        updatedAt: "Checked this week",
        price: "₹42,490",
        oldPrice: "₹49,490",
        save: "Save ₹7,000",
        image:
          "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#f59e0b",
        link: "#",
      },
    ],
  },
  {
    key: "mobiles",
    title: "Best Phones Under ₹20,000",
    accent: "#60a5fa",
    items: [
      {
        id: 4,
        tag: "HOT DEAL",
        tagColor: "#60a5fa",
        title: "iQOO Budget 5G Phone",
        subtitle: "Smooth performance · Fast charging",
        bestFor: "Gaming on a budget",
        avoidIf: "Camera is your top priority",
        saverNestScore: {
          overall: 8.4,
          value: 8.8,
          performance: 8.9,
          reliability: 7.8,
        },
        reason: {
          summary:
            "Best if you want strong performance and gaming value without overspending.",
          pros: [
            "Strong performance for the price",
            "Good option for gaming-focused buyers",
            "Fast charging improves daily convenience",
          ],
          cons: ["May not offer the best camera experience in this range"],
        },
        trustLine: "Best performance value",
        updatedAt: "Checked this week",
        price: "₹12,999",
        oldPrice: "₹16,999",
        save: "Save ₹4,000",
        image:
          "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#60a5fa",
        link: "#",
      },
      {
        id: 5,
        tag: "TOP SELLER",
        tagColor: "#a78bfa",
        title: "AMOLED Display Smartphone",
        subtitle: "Slim body · Good cameras",
        bestFor: "Display & media lovers",
        avoidIf: "You want max gaming power",
        saverNestScore: {
          overall: 8.2,
          value: 8.0,
          performance: 7.7,
          reliability: 8.4,
        },
        reason: {
          summary:
            "Best pick for users who care more about display quality and daily experience.",
          pros: [
            "AMOLED display gives a better viewing experience",
            "Slim design feels more premium in hand",
            "Good cameras for normal daily use",
          ],
          cons: ["Performance may be weaker than performance-first rivals"],
        },
        trustLine: "Best display under 20k",
        updatedAt: "Checked this week",
        price: "₹17,499",
        oldPrice: "₹20,999",
        save: "Save ₹3,500",
        image:
          "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#a78bfa",
        link: "#",
      },
      {
        id: 6,
        tag: "BEST VALUE",
        tagColor: "#f87171",
        title: "Compact 5G Smartphone",
        subtitle: "Clean UI · Good battery",
        bestFor: "Balanced everyday users",
        avoidIf: "You want premium extras",
        saverNestScore: {
          overall: 8.3,
          value: 8.9,
          performance: 7.9,
          reliability: 8.1,
        },
        reason: {
          summary:
            "Best value choice for buyers who want a balanced phone for everyday use.",
          pros: [
            "Balanced performance for daily tasks",
            "Clean UI improves the user experience",
            "Good battery backup for normal usage",
          ],
          cons: [
            "May lack standout premium features compared with pricier phones",
          ],
        },
        trustLine: "Most balanced pick",
        updatedAt: "Checked this week",
        price: "₹14,999",
        oldPrice: "₹18,999",
        save: "Save ₹4,000",
        image:
          "https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#f87171",
        link: "#",
      },
    ],
  },
  {
    key: "audio",
    title: "Best Earbuds Under ₹3,000",
    accent: "#f87171",
    items: [
      {
        id: 7,
        tag: "48% OFF",
        tagColor: "#f87171",
        title: "Wireless Earbuds Pro",
        subtitle: "30hr battery · IPX5 · ANC",
        bestFor: "Travel & commute",
        avoidIf: "You want premium sound quality",
        saverNestScore: {
          overall: 8.2,
          value: 8.8,
          performance: 7.7,
          reliability: 8.0,
        },
        reason: {
          summary:
            "Best for commuters and students who want affordable ANC and long battery life.",
          pros: [
            "ANC is rare at this low price",
            "Long battery life is useful for travel and classes",
            "IPX5 rating adds protection for daily use",
          ],
          cons: ["Sound quality may not match premium earbuds"],
        },
        trustLine: "Best travel features",
        updatedAt: "Checked this week",
        price: "₹1,299",
        oldPrice: "₹2,499",
        save: "Save ₹1,200",
        image:
          "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#f87171",
        link: "#",
      },
      {
        id: 8,
        tag: "BEST BASS",
        tagColor: "#4ade80",
        title: "Over Ear Headphones",
        subtitle: "Deep bass · Long battery",
        bestFor: "Bass-heavy listening",
        avoidIf: "You want easy portability",
        saverNestScore: {
          overall: 8.1,
          value: 8.3,
          performance: 8.2,
          reliability: 7.8,
        },
        reason: {
          summary:
            "Best for users who want fuller sound, stronger bass, and longer listening sessions.",
          pros: [
            "Strong bass response for music lovers",
            "More immersive sound than tiny earbuds",
            "Long battery supports extended listening",
          ],
          cons: ["Bulkier and less portable than earbuds or neckbands"],
        },
        trustLine: "Best bass value",
        updatedAt: "Checked this week",
        price: "₹2,299",
        oldPrice: "₹3,799",
        save: "Save ₹1,500",
        image:
          "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#4ade80",
        link: "#",
      },
      {
        id: 9,
        tag: "EDITOR PICK",
        tagColor: "#22d3ee",
        title: "Neckband Earphones",
        subtitle: "Lightweight · Good mic",
        bestFor: "Calls & all-day wear",
        avoidIf: "You want a fully wireless look",
        saverNestScore: {
          overall: 8.0,
          value: 8.7,
          performance: 7.5,
          reliability: 8.1,
        },
        reason: {
          summary:
            "Best for calls, daily travel, and users who prefer practical all-day comfort.",
          pros: [
            "Good microphone for calls and meetings",
            "Lightweight design is comfortable for long wear",
            "Easy to use while commuting or working",
          ],
          cons: ["Less premium feel than true wireless earbuds"],
        },
        trustLine: "Best for calling",
        updatedAt: "Checked this week",
        price: "₹999",
        oldPrice: "₹1,799",
        save: "Save ₹800",
        image:
          "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#22d3ee",
        link: "#",
      },
    ],
  },
  {
    key: "wearables",
    title: "Best Smartwatches Under ₹5,000",
    accent: "#a78bfa",
    items: [
      {
        id: 10,
        tag: "50% OFF",
        tagColor: "#a78bfa",
        title: "Smart Fitness Band",
        subtitle: "Heart rate · Sleep · 10-day battery",
        bestFor: "Basic health tracking",
        avoidIf: "You want full smartwatch features",
        saverNestScore: {
          overall: 8.0,
          value: 8.8,
          performance: 7.2,
          reliability: 8.0,
        },
        reason: {
          summary:
            "Best for buyers who want affordable health tracking without paying for extras they won’t use.",
          pros: [
            "Tracks basic health metrics at low cost",
            "Good battery life reduces charging hassle",
            "Simple and practical for fitness beginners",
          ],
          cons: ["Fewer smart features than full smartwatches"],
        },
        trustLine: "Best beginner fitness pick",
        updatedAt: "Checked this week",
        price: "₹1,499",
        oldPrice: "₹2,999",
        save: "Save ₹1,500",
        image:
          "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#a78bfa",
        link: "#",
      },
      {
        id: 11,
        tag: "TOP WATCH",
        tagColor: "#4ade80",
        title: "Bluetooth Calling Watch",
        subtitle: "Large display · Fitness modes",
        bestFor: "Calling on a budget",
        avoidIf: "You care most about battery life",
        saverNestScore: {
          overall: 8.2,
          value: 8.5,
          performance: 8.0,
          reliability: 7.9,
        },
        reason: {
          summary:
            "Best if your priority is big-screen convenience and Bluetooth calling on a budget.",
          pros: [
            "Bluetooth calling adds practical daily use",
            "Large display is easier to read and use",
            "Multiple fitness modes improve versatility",
          ],
          cons: ["Battery life may be lower than simpler fitness bands"],
        },
        trustLine: "Best calling smartwatch",
        updatedAt: "Checked this week",
        price: "₹1,999",
        oldPrice: "₹3,499",
        save: "Save ₹1,500",
        image:
          "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#4ade80",
        link: "#",
      },
      {
        id: 12,
        tag: "VALUE PICK",
        tagColor: "#f59e0b",
        title: "Sport Smartwatch",
        subtitle: "AMOLED · Long battery",
        bestFor: "Premium feel under budget",
        avoidIf: "You want flagship-grade accuracy",
        saverNestScore: {
          overall: 8.4,
          value: 8.7,
          performance: 7.9,
          reliability: 8.1,
        },
        reason: {
          summary:
            "Best value choice for users who want a sharper display and better premium feel under budget.",
          pros: [
            "AMOLED display looks sharper and more premium",
            "Long battery life improves day-to-day convenience",
            "Better style appeal than cheaper basic watches",
          ],
          cons: ["Accuracy and app experience may not match high-end brands"],
        },
        trustLine: "Best display value",
        updatedAt: "Checked this week",
        price: "₹2,799",
        oldPrice: "₹4,299",
        save: "Save ₹1,500",
        image:
          "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=900&q=80",
        cta: "Check today’s price",
        accent: "#f59e0b",
        link: "#",
      },
    ],
  },
];